# Generated by Django 4.2.23 on 2025-09-14 04:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('purpose', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('memory', models.JSONField(blank=True, default=dict)),
                ('agent_state', models.JSONField(blank=True, default=dict)),
                ('toolkits', models.JSONField(blank=True, default=list)),
                ('suggested_task_prompts', models.JSONField(blank=True, default=list)),
                ('suggested_job_prompts', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='AgentKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('nodes_count', models.IntegerField(default=0)),
                ('relationships_count', models.IntegerField(default=0)),
                ('documents_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_knowledge',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused')], default='active', max_length=16)),
                ('trigger_type', models.CharField(choices=[('composio', 'composio'), ('schedule', 'schedule'), ('webhook', 'webhook')], max_length=16)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('created_by_user_id', models.UUIDField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_jobs',
            },
        ),
    ]
