# Generated by Django 4.2.23 on 2025-09-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='chat.thread'),
        ),
        migrations.AddField(
            model_name='agentknowledge',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user_id'], name='agent_user_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['agent', 'status'], name='job_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['trigger_type'], name='job_trigger_type_idx'),
        ),
        migrations.AddIndex(
            model_name='agentknowledge',
            index=models.Index(fields=['agent'], name='agent_knowledge_agent_idx'),
        ),
    ]
