# Generated by Django 4.2.23 on 2025-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='chat_system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='chat_tool_whitelist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='inbox_system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='inbox_tool_whitelist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
