# Generated by Django 4.2.23 on 2025-09-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_chat_system_prompt_agent_chat_tool_whitelist_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='job_trigger_type_idx',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='chat_system_prompt',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='chat_tool_whitelist',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='inbox_system_prompt',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='inbox_tool_whitelist',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trigger_type',
        ),
    ]
