# Generated by Django 4.2.23 on 2025-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_job_job_trigger_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='connected_account_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='toolkit_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='trigger_slug',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['toolkit_slug'], name='job_toolkit_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['connected_account_id'], name='job_connected_account_idx'),
        ),
    ]
