# Generated by Django 4.2.23 on 2025-09-14 04:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='agents.agent')),
            ],
            options={
                'db_table': 'chat_threads',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('waiting_human', 'waiting_human'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=32)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('checkpoint_ns', models.CharField(blank=True, max_length=128, null=True)),
                ('checkpoint_id', models.CharField(blank=True, max_length=128, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agents.agent')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='chat.thread')),
            ],
            options={
                'db_table': 'chat_runs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system'), ('tool', 'tool')], max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('events_json', models.JSONField(blank=True, default=dict)),
                ('tool_name', models.CharField(blank=True, default='', max_length=200)),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=200)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.thread')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='GraphCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_ns', models.CharField(blank=True, default='default', max_length=128)),
                ('checkpoint_id', models.CharField(max_length=128)),
                ('parent_id', models.CharField(blank=True, default='', max_length=128)),
                ('writes', models.JSONField(default=list)),
                ('state', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='chat.run')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='chat.thread')),
            ],
            options={
                'db_table': 'chat_graph_checkpoints',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user_id'], name='chat_thread_user_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['thread'], name='chat_run_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['correlation_id'], name='chat_run_corr_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'sequence'], name='chat_msg_thread_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='graphcheckpoint',
            index=models.Index(fields=['thread', 'created_at'], name='graph_ckpt_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='graphcheckpoint',
            index=models.Index(fields=['run', 'created_at'], name='graph_ckpt_run_idx'),
        ),
        migrations.AddIndex(
            model_name='graphcheckpoint',
            index=models.Index(fields=['checkpoint_id'], name='graph_ckpt_id_idx'),
        ),
    ]
