# Generated by Django 4.2.23 on 2025-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_ambient',
            field=models.BooleanField(default=False),
        ),
    ]
