# Generated by Django 4.2.23 on 2025-09-14 04:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('correlation_id', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body_json', models.JSONField(blank=True, default=dict)),
                ('item_type', models.CharField(choices=[('job_result', 'job_result'), ('human_action_request', 'human_action_request')], default='job_result', max_length=32)),
                ('status', models.CharField(choices=[('new', 'new'), ('read', 'read'), ('archived', 'archived')], default='new', max_length=32)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_items', to='agents.agent')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_items', to='chat.run')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_items', to='chat.thread')),
            ],
            options={
                'db_table': 'inbox_items',
                'indexes': [models.Index(fields=['user_id'], name='inbox_user_idx'), models.Index(fields=['status'], name='inbox_status_idx'), models.Index(fields=['correlation_id'], name='inbox_corr_idx')],
            },
        ),
    ]
