# Generated by Django 4.2.23 on 2025-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('toolkit_slug', models.CharField(db_index=True, max_length=100)),
                ('connected_account_id', models.CharField(max_length=128, unique=True)),
                ('auth_config_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'toolkit_slug'], name='connections_user_id_bdc2c5_idx')],
            },
        ),
    ]
